drop table if exists statistics;

create table if not exists statistics
(
    hit_id  bigint generated by default as identity,
    app     varchar(255) not null,
    uri     varchar(255) not null,
    ip      varchar(255) not null,
    created timestamp    not null,
    constraint statistics_pk primary key (hit_id)
);